Usertoken
wolox-training/fec-rails pull request #5
Opened 2019-05-02 22:43 UTC by fedecavazzoli

Now it is all working according to the task in trello :)

2019-05-03 16:25 UTC, jhonmunoz submitted a review, later dismissed

2019-05-03 19:24 UTC, cquiro requested changes
Add the log folder to the .gitignore file.

2019-05-03 21:47 UTC, floresv commented on .rubocop.yml
> +  Enabled: false
Why? 🤔

2019-05-03 21:47 UTC, floresv commented on Gemfile
> +gem 'haml'
Why?

2019-05-03 21:48 UTC, floresv commented on Gemfile
> +gem 'rack-cors', :require => 'rack/cors'
Are you really need this? https://github.com/lynndylanhurley/devise_token_auth/blob/master/docs/config/cors.md

2019-05-03 21:49 UTC, floresv commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable and :omniauthable
Remove commented code

2019-05-03 21:50 UTC, floresv requested changes
I agree with 🚗 🔑

2019-05-06 21:14 UTC, floresv reviewed
It's good but remove `log/development.log`

2019-05-07 18:22 UTC, floresv commented
I still see the log development file, please remove it.

2019-05-07 20:20 UTC, floresv approved these changes
Looks good to me

2019-05-08 18:29 UTC, cquiro approved these changes

2019-05-08 18:38 UTC, merged